sudo: required
dist: bionic
language: generic

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++
  - g++ -o Progression.out Progression.cpp

notifications:
  email:
    on_success: never
    on_failure: always
script:
  - g++ -o Progression.out Progression.cpp
  - ./Progression.out 5 -v
  - ./Progression.out 12 -v
  - ./Progression.out 65 -v
  - ./Progression.out 235 -v
  - ./Progression.out 23432 -v
  - ./Progression.out 1143242 -v
